import { Palette } from "./palette.enum";

/** Colors for the VSCode UI */
export default {
  colors: {
    "activityBar.activeBorder": Palette.Type,
    "activityBar.background": Palette.Background,
    "activityBar.foreground": Palette.Type,
    "activityBar.inactiveForeground": Palette.Activity_bar_icon, // plugin icons on the left bar
    "activityBarBadge.background": Palette.Keyword,
    "activityBarBadge.foreground": Palette.Variable,
    "button.background": Palette.Used_properties,
    "editor.background": Palette.Background,
    "editor.foreground": Palette.Variable,
    "editorGroupHeader.tabsBackground": Palette.Background,
    "editorGutter.background": Palette.Background,
    "editorIndentGuide.activeBackground": Palette.Type,
    "editorIndentGuide.background": Palette.Line_separator,
    "editorInlayHint.parameterForeground": Palette.Comment,
    "editorLineNumber.activeForeground": Palette.Used_properties,
    "editorLineNumber.foreground": Palette.Line_numbers_rulers,
    "editorOverviewRuler.border": Palette.Line_separator,
    "editorRuler.foreground": Palette.Line_numbers_rulers,
    "list.activeSelectionBackground": Palette.Active_list_item,
    "menu.selectionBackground": Palette.Type,
    "scrollbar.shadow": Palette.Background,
    "sideBar.background": Palette.Background,
    "sideBar.border": Palette.Line_separator,
    "sideBarSectionHeader.background": Palette.Background,
    "sideBarSectionHeader.border": Palette.Line_separator,
    "sideBarTitle.foreground": Palette.Variable,
    "statusBar.background": Palette.Used_properties,
    "tab.activeBackground": Palette.Tabs_background,
    "tab.activeBorder": Palette.Keyword,
    "tab.activeBorderTop": Palette.Keyword,
    "tab.inactiveBackground": Palette.Background,
    "titleBar.activeBackground": Palette.Background,
    "tree.indentGuidesStroke": Palette.Type,
    focusBorder: Palette.Type,
  },
};
